/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MultipleArbitrableTransaction_ABI } from "./MultipleArbitrableTransaction_ABI";
export * as factories from "./factories";
export { MultipleArbitrableTransaction_ABI__factory } from "./factories/MultipleArbitrableTransaction_ABI__factory";
